title: "CloverX"

plugins: [jekyll-paginate]

paginate: 5
paginate_path: "/archive/page:num/"

# default_theme: "light"

footer:
  title: "CloverX"
  author: 
    name: "Yasas"
    url: "https://www.ysenarath.com"